@startuml
'https://plantuml.com/class-diagram

left to right direction

class Property {
String property_type
Double price
int surface
int rooms_count
String description
String[] media_uri_list
String address
Property_status status
Date market_entry
Date sold
String agent
}

enum Property_status {
AVAILABLE
SOLD
}

Property "1" *-- "1" Property_status

@enduml